using System;

// Token: 0x0200049D RID: 1181
public static class TwitchAuthLandingPages
{
	// Token: 0x040021EA RID: 8682
	public static readonly string SuccessLandingPage = "<html><head><title>Shadows of Doubt Twitch Authorization</title></head><style>body{background-color: #000;background-image: url(https://colepowered.com/wp-content/uploads/2023/09/SodMenuBG.webp);-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;background-repeat: no-repeat;}.auth-box{order: 2;width: fit-content;height: fit-content;border-color: #d5706969;border-style: double;border-width: 3.5px;box-shadow: 0px 0px 2px 2px #c01d1d30;}.logo{order: 1;margin-top: 100px;width: 500px;height: 300px;}.foot-note{order: 3;flex: 0 1 40px;margin-top: auto;font-family: sans-serif;text-align: center;}.logo img{width: 100%;height: 100%;object-fit: cover;overflow: hidden;}.align-these{display: flex;flex-direction: column;margin-top: 0;align-items: center;justify-content: space-between;flex-wrap: nowrap;height: 96vh;}h2{margin: 10px 40px 10px 40px;color: #ffadc7;text-align: center;font-family: serif;letter-spacing: .1em;text-shadow: 0 0 10px #c01d1d, 0 0 10px #c01d1d, 0 0 30px #e6000023, 0 0 20px #e6000023, 0 0 20px #e6000023, 0 0 20px #e6000023, 0 0 30px #e6000023;}h4{color: white;}</style><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Document</title></head><body><div class='align-these'><div class='logo'><img src='https://colepowered.com/wp-content/uploads/2023/09/shadowsofdoubt_logo.png'></div><div class='auth-box'><h2>TWITCH LOGIN COMPLETE</h2></div><div class='foot-note'><h4>You may now return to <em>Shadows of Doubt</em>. Good luck gumshoes.</h4></div></div>";

	// Token: 0x040021EB RID: 8683
	public static readonly string RejectedLandingPage = "<html><head><title>Shadows of Doubt Twitch Authorization</title></head><style>body{background-color: #000;background-image: url(https://colepowered.com/wp-content/uploads/2023/09/SodMenuBG.webp);-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;background-repeat: no-repeat;}.auth-box{order: 2;width: fit-content;height: fit-content;border-color: #d5706969;border-style: double;border-width: 3.5px;box-shadow: 0px 0px 2px 2px #c01d1d30;}.logo{order: 1;margin-top: 100px;width: 500px;height: 300px;}.foot-note{order: 3;flex: 0 1 40px;margin-top: auto;font-family: sans-serif;text-align: center;}.logo img{width: 100%;height: 100%;object-fit: cover;overflow: hidden;}.align-these{display: flex;flex-direction: column;margin-top: 0;align-items: center;justify-content: space-between;flex-wrap: nowrap;height: 96vh;}h2{margin: 10px 40px 10px 40px;color: #ffadc7;text-align: center;font-family: serif;letter-spacing: .1em;text-shadow: 0 0 10px #c01d1d, 0 0 10px #c01d1d, 0 0 30px #e6000023, 0 0 20px #e6000023, 0 0 20px #e6000023, 0 0 20px #e6000023, 0 0 30px #e6000023;}h4{color: white;}</style><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Document</title></head><body><div class='align-these'><div class='logo'><img src='https://colepowered.com/wp-content/uploads/2023/09/shadowsofdoubt_logo.png'></div><div class='auth-box'><h2>USER AUTHORIZATION FAILED</h2></div><div class='foot-note'><h4>There was an issue linking your account.<br>Please verify your Twitch settings and try again.</h4></div></div>";
}
